### PR TITLE
Regex Based Validation for String Features.

### PR DESCRIPTION
**Pull request by NarraVivek**
**What's in the PR**
In this PR we will observe the implementation of a feature into the layers field under the project settings tab of the INCEpTION application as described in the Issue. The motive of this feature is to allow the user to specify a Regular expression which could be referenced and used in the string fields seen in the feature details of a layer selected. Verification of the tags should also be performed to check whether the tags are present already in the tagsets.

Issue reference: https://github.com/inception-project/inception/issues/1268
**NOTE**
There is no implementation yet, this PR is created early to check progress and understand few other facts about this issue.  A random change has been made to raise a Request.

**Findings**
The Major changes or implementations which are to be made are located in the WebAnno application "PrimitiveUimaFeatureSupport.setFeatureValue(...)", these packages are accessed by the inception using a link. There are code instances in INCEpTION where this function is utilized.
As described in the Issue and the discussions in it, we have come to a conclusion that the changes to be made should be done in WebAnno repository. 

Capture

This is the snippet of the code present in WebAnno application where the feature is to be implemented. 

**Further Work**
Need clarification on this 

As the packages are in another package from a different location, should we clone the WebAnno application and make the changes there? 

Should we make two Pull requests in both the repositories being , current  [https://github.com/munterkalmsteiner/inception](url) and [https://webanno.github.io/webanno](url)

As the Issue states the Admin or user should be able to input certain Regex statements, a New String field in the Layers configuration page be created?

### CODE REVIEW

**Comment by NarraVivek** [comment]
There were only two java files which used the PrimitiveUimaFeatureSupport() in inception(committed above) from WebAnno. It is observed that all the implementations which have to be done regarding this function are to be done in the WebAnno repository. Initially, the instances which we found in other files are also proving not useful. 

Do we need to make the changes in WebAnno repository? Please give us some idea about how to proceed.

**Comment by NarraVivek** [comment]
We have tried to solve the issue from INCEpTION for the feature "Regex-based validation" as mentioned above. The attempt to this solution is present in the webanno repository with the PR link https://github.com/webanno/webanno/pull/1504

A Related UI implementation of this PR is below : 
regex

**Comment by NarraVivek** [comment]
@munterkalmsteiner please review this PR

**Comment by munterkalmsteiner** [comment]
@NarraVivek, did you see reckart's [comment](https://github.com/webanno/webanno/pull/1504#issuecomment-546722261)? As you did not sign the contribution agreement, you can create a new pull request against [my fork](https://github.com/munterkalmsteiner/webanno) of webanno, which I just created. Then delete the pull request you made at upstream of webanno.

**Comment by NarraVivek** [comment]
Yes, I have read Reckart's comment. I was not sure about the pulling request in webanno as your fork was not present when we had to submit. We will now create a new one in your forked repository and get back to you soon.

**Comment by munterkalmsteiner** [comment]
Good work. Implemented [here](https://github.com/munterkalmsteiner/webanno/pull/2).

**Pull request closed without merging**
