### PR TITLE
#1125Add button to add missing labels to an ontology.

### PR DESCRIPTION
**Pull request by NovemberChopin**
Firstly,we need to add a new button in ConceptTreePanel.html to auto-generate labels. Secondly, we need to define a new method to deal the click event of this button. When the button is clicked, the method autoCreateLabel(AjaxRequestTarget aTarget) will be invocked. In this method, we firstly go through each resource in the specific KnowledgeBase.We get an object of the KnowledgeBaseService class through the automatic injection of the Spring framework.All resources belonging to the current knowledge base are obtained by calling the object's listAllConcepts method (using a specific knowledge base as a parameter).Next, we need to iterate through all the resources we get. For each resource object, determine whether the current resource contains a tag by calling the getUiLabel() method and the getIdentifier() method. If the current resource does not contain a label, create a label attribute for it.
**What's in the PR**
* ...

**How to test manually**
* ...

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
inception-ui-kb/src/main/java de.tudarmstadt.ukp.inception.ui.kb.ConceptTreePanel.html
inception-ui-kb/src/main/java de.tudarmstadt.ukp.inception.ui.kb.ConceptTreePanel.java

### CODE REVIEW

**Comment by munterkalmsteiner** [comment]
@NovemberChopin when I checkout and run your code, I get a runtime exception when I go to a knowledgebase:
image

The reason seems to be your code (autoCreateLabel).

**Comment by NovemberChopin** [comment]
I saw that can I modify it and submit it again?

**Comment by munterkalmsteiner** [comment]
@NovemberChopin sure go ahead. Just update in this branch.

**Comment by munterkalmsteiner** [comment]
Still getting an error:
image

If I comment out your code (i.e. remove `add(new LambdaAjaxLink("autoCreateLabel", this::autoCreateLabel));`), I get no exception. This indicates there is still a problem with your code.

**Comment by NovemberChopin** [comment]
Work done so far based on the solution:
1.add button to KB settings page
2.go through each resource in the KB
3.use getUiLabel() from KBObject to extract a human-readable label 

Unfinished work: create a label property

We want to create a label property. We come up with two solutions.
Solution 1:
We want to do this by simulating click events.
When we encounter an empty statements, we can click  button of creating statements. And then we selecte a property and save it.




This process will be imitated when I click my button. 
Challenges  about solution 1:
the button creating statement will trigger this method actionAdd().
(inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementsPanel.java)
the button saving changed will trigger this method actionSave().
(inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/stmt/StatementEditor.java)

When I try to simulate the process, I  create a KBStatement for every concept missing label. And then we invoke upsertStatement() from KnowledgeBaseService to persist the modified statement and actionCancelExistingStatement() from StatementEditor to modify ViewMode and send notification to listeners. I think this process is right. But  we don't see the desired effect on my machine. I think we might need to update all the concepts iteratively. But I don’t know how to update all the concepts iteratively. Also, I don't understand the relationship between KBStatement and KBProperty. This may also influence me to solve this problem. I think it is difficult for anyone to understand the knowledge base completely.

Solution 2:
We want to do this by finding some method in the process initializing knowledge base.

We already know that when we create a Wine Ontology knowledge base, all of its concepts have label property. So I want to find some method to create label property in the process of initializing the knowledge base.

Challenges  about solution 2:
location of initializing the knowledge base:
inception-ui-kb/src/main/java/de/tudarmstadt/ukp/inception/ui/kb/project/AccessSpecificSettingsPanel.java

When I check the code, I can't find any useful information about creating the label property. So I use AmaterasUML to create UML diagrams. But I still don’t understand how to create the label property in the process initializing the knowledge base. So I finally choose the solution 1.

**Comment by munterkalmsteiner** [comment]
I think you were somewhat on the right way, but maybe my explanations got lost in translation. Still sufficient for a passing grade as you made an effort to find the right solution.

**Pull request closed without merging**
