### PR TITLE
  #[1117] - [Ability to export recommender model]

### PR DESCRIPTION
**Pull request by waqasshafi**
#[1117] - [Ability to export recommender model]

[1 We tried to implement the front end and back end functionality of the Export button inthe following files
 RecommenderInfoPanel.html
 RecommenderInfoPanel.java]
[2 We have created the Export model in RecommederEngine]
[3 While implementing in StringMatchingRecommender.java we used the train method in exportModel() to have user details and CAS related information.]
[4 Now we are implementing it in child/reference classes.]
[5 How to cast CAS model to outputstream?]

**What's in the PR**
* We created the export button in the recommender model and we have created the methods for the export button.

**How to test manually**
* By running the application on the local server 

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

### CODE REVIEW

**Comment by munterkalmsteiner** [comment]
@waqasshafi should I review this code? When I check it out, it does not compile...

**Comment by waqasshafi** [comment]
@munterkalmsteiner I have just run this branch on my machine and it's working fine. See the attached screenshot.

A
B
C
D

**Comment by munterkalmsteiner** [comment]
@waqasshafi you did not commit and push all your changes. When I checkout your code, I get compilation errors:
image

Once you pushed all your changes, please request a review.

**Comment by waqasshafi** [comment]
@munterkalmsteiner I have committed all the changes and verify that there is no compilation error in this code. Kindly review this.

**Review by munterkalmsteiner — CHANGES_REQUESTED** [review]
Hm, now the code compiles, but when I'm in the annotation page and want to open the recommender tab, in order to download the model, I get a runtime exception:
image

There's a null pointer exception here:
`at de.tudarmstadt.ukp.inception.recommendation.sidebar.RecommendationSidebar.findMismatchedRecommenders(RecommendationSidebar.java:166) ~[inception-recommendation-0.13.0-SNAPSHOT.jar:?]`

I have created a StringmatchRecommender in the project. Do I need to configure anything else to make it work?

**Comment by waqasshafi** [comment]
@munterkalmsteiner When I tried to open the recommender model in annotation tab its working fine. See the attached screenshot but when I try to click on the Export button that we have implemented I also got the same error. This is the thing we have already mentioned on the top that.
1 We tried to implement the front end and back end functionality of the Export button in the following files
RecommenderInfoPanel.html
RecommenderInfoPanel.java
2 We have created the Export model in RecommederEngine
3 While implementing in StringMatchingRecommender.java we used the train method in exportModel() to have user details and CAS related information.
4 Now we are implementing it in child/reference classes.
5 How to cast CAS model to outputstream?
The only isuue we are facing while implementing the backend functionality is to cast CAS model to outputstream. Rest of the functionality is implemented. 
Inception_1

**Comment by munterkalmsteiner** [comment]
The implementation looks ok for the front-end (which is the easy part), but the back-end does not work as intended. You cannot "cast" the CAS to an Java output stream. You probably need to implement some sort of conversion. reckart has explained the idea [here](https://github.com/inception-project/inception/issues/1117#issuecomment-544495839), i.e. the output format depends on the type of model. You have had the right ideas, I think, but were not able to implement them. Still, this is good enough for a pass grade.

**Pull request closed without merging**
