### PR TITLE
[Mi11]:Override the "equals" method.

### PR DESCRIPTION
**Pull request by AbhinavRamKola**
**What's in the PR**

The equals() method in the code is overridden to compare the objects and find the memory allocation.

### CODE REVIEW

**Review by munterkalmsteiner — CHANGES_REQUESTED** [review]
Hm, I don't think this change is necessary. There was no class that implements `equals()` but not `hashcode()`. As such, this is not a problem. Also, your implementations do not consider the instance variables of the subclass, but you call `equals()` and `hashcode()` of the parent classes only. This does, in my opinion, not improve the code (just increases it's size). 
Please provide an argument why this particular change is beneficial.

**Comment by AbhinavRamKola** [comment]
Yes, I realized this is a false positive error after i uploaded. I made this change because the tool has suggested it and at that time i did not consider this possibility. I agree that this change was unnecessary.

**Review by AbhinavRamKola — COMMENTED** [review]
There is no need to override "equals" method. It is a false positive error.

**Comment by munterkalmsteiner** [comment]
Hm, ok. I would suggest you to post a screenshot of sonarcube's finding here as it would be interesting to see this false positive. After that, you can close the pull request.

**Comment by AbhinavRamKola** [comment]
WhatsApp Image 2019-10-18 at 1 28 08 PM
WhatsApp Image 2019-10-18 at 1 28 08 PM (1)

**Comment by munterkalmsteiner** [comment]
Agree that these are false positives.

**Pull request closed without merging**
