### PR TITLE
[Issue1098] If current document appears in external search results, highlight it 

### PR DESCRIPTION
**Pull request by silence1016**
Each time the search result is reloaded, a new ResultRowView type object is generated. We need to add statements in the definition of the ResultRowView class to determine whether the search result of the left sidebar is clicked. searchState.getSelectedResult() == null. Before without clicking  the search result of the sidebar on the left side, add the title content to the link, otherwise you need to use if(documentTitle.equals(rowView.title)) to determine which of the 8 search results is the same as the title value of the current click result. Returning true search results's title value is highlighted and added to the link.Returning false directly add to the link without highlights. The following statement is used for the highlight title value: documentTitle="<mark>"+documentTitle+"</mark>";
rowView.link.add(newLabel("title",documentTitle).setEscapeModelStrings(false));

**What's in the PR**
Add some new code statements. So if the current document appears in the list of external search results, highlight its row in the external search results.

**How to test manually**
If the result‘s title of external search sidebar  equals to the document ID of the currently open document,highlight the title

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
inception\inception-ui-external-search\src\main\java\de\tudarmstadt\ukp\inception\app\ui\externalsearch\sidebar

### CODE REVIEW

**Comment by munterkalmsteiner** [comment]
Hi @silence1016 can you post here a screenshot of how your solution looks like?

**Comment by silence1016** [comment]
> Hi @silence1016 can you post here a screenshot of how your solution looks like?



Hi, in the first picture it shows a result when the opened file is not in the sidebar search result. There is not a link highlighted. In the second picture it shows that  the corresponding link will be highlighted  when we onclick one result in the sidebar.

**Review by munterkalmsteiner — COMMENTED** [review]
Hm, I tried to replicate what you have shown in your screenshots, but was not able to. See below:
image

I've checked out your feature branch, made a search, imported the document. Then I moved to another document, went back to the imported document and expected it to be highlighted in the search bar. However that was not the case.

One strange thing is that your screenshots show verion 0.13.0 of inception, while the code you committed is 0.12.0. How is that possible?

**Comment by silence1016** [comment]
@munterkalmsteiner  The code I am running is forked from the upstream, and the modified code is based on this. The code I submitted is the previous version of the fork I used from your repository, not the latest one. 
Is this the reason? If this is the case, how should I fix this problem next?

**Comment by munterkalmsteiner** [comment]
@silence1016 ok, I see. I have now pulled also the upstream changes locally and merged them with your branch. still no highlight in the search box, though:
image

I'd suggest you to push all code (also your merge with upstream) to this branch so we are 100% that we run the same code.

**Comment by silence1016** [comment]
@munterkalmsteiner Our design idea: When entering the annotation interface, the search results are not matched with the annotation document ID on the right. Only when we click on the result of the search results on the left side will it match the document ID on the right side. If it is correct, the ID of the search result on the left side will be highlighted.
So the reason for this case may be that you didn't click on the search results. You can try again.If it still can' work, can we re-pull the request and submit it?

**Comment by munterkalmsteiner** [comment]
Ah, ok. Now I can see the highlighting also. However, I don't think this works as intended. The [issue](https://github.com/inception-project/inception/issues/1098) proposes the following solution:
If the current document appears in the list of external search results, highlight its row in the external search results.

This is not the same as your solution. What I would have expected is the following:
1) I open a document for annotation 
2) I do a search that contains the currently opened document
3) Once the search is completed, the currently opened document is highlighted in the search results

Do you agree that this is the wanted behavior described in the issue?

**Comment by silence1016** [comment]
@munterkalmsteiner I agree with you. So we have modified the code according to the above requirements and the new code are working properly. Can we re-pull the request and resubmit it now?

**Comment by munterkalmsteiner** [comment]
@silence1016 sure, just push a new commit and I'll test the code.

**Review by munterkalmsteiner — APPROVED** [review]
Good work! The functionality is, I think, implemented as intended. I would have some comments before the code would be merged, but as the code will not be contributed upstream, I'm fine with the current pull request.

**Pull request closed without merging**
